name: Docker Example
on:
  workflow_dispatch:

jobs:
  Task2:
    runs-on: ubuntu-latest
    steps:
      - name: use checkout
        uses: actions/checkout@v4
      - name: setup npm framework  
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: run npm install
        run: npm install

      - name: make zip
        run: |
         zip -r app-bundle.zip . \
         -x ".git/*" \
         -x ".github/*"
        
      - name: bundle the code in a zip
        uses: actions/upload-artifact@v4
        with: 
          name: app-package
          path: app-bundle.zip

      - name: Run unit tests and save report
        run: |
          mkdir -p test-report
          npm test --silent > test-report/unit-tests.txt || true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: test-report/unit-tests.txt

      - name: log into docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile2
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          
