name: Dependancies Example
on:
  workflow_dispatch:

jobs:
  Task2:
    runs-on: ubuntu-latest
    steps:
      - name: use checkout
        uses: actions/checkout@v4
      - name: setup npm framework  
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: verification
        run: ls -alhR
            
